baseURL: "https://evanjarrett.com"
languageCode: "en-us"
title: "Evan"
theme: hugo-profile
pluralizeListTitles: false

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blog
      weight: 1
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Evan Jarrett"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    #brandName: "Hugo Profile" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: true
      disableAchievements: true
      disableContact: true
      disableGallery: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Evan."
    subtitle: "I build things for the web"
    content: |-
        Dedicated Software Engineer with over 8 years of hands-on experience in Kubernetes, PHP, MySQL, and Linux. My journey in technology has been fueled by a relentless curiosity, driving me to explore a wide array of languages and tools, including Python, Go, and Docker. My commitment to mentorship and teamwork has allowed me to foster collaboration and effective problem-solving within my teams. Embracing a holistic approach, I advocate for rigorous testing, code review, and continuous improvement. Let's connect and drive innovation together!
    image: /images/avatar.jpg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "#about"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/evanjarrett/
        - icon: fab fa-linkedin
          url: https://linkedin.com/in/evanjarrett/
      customIcons:

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.jpg"
    content: |-
      Software Engineer with over 8 years of professional experience in Kubernetes, PHP, MySQL, and Linux. Continues to improve skills in other technologies by applying them to personal projects and hobbies. Effective mentor and team lead committed to helping others. Adamant about proper testing and code review.
    skills:
      enable: true
      items:
        - "Kubernetes"
        - "PHP"
        - "MySQL"
        - "Python"
        - "Docker"
        - "Go"
        - "Git"
        - "Bash"
        - "Linux"

  # Experience
  experience:
    enable: true
    items:
      - job: "Senior DevOps Engineer"
        company: "Avigilon Alta"
        companyUrl: "https://www.avigilon.com/"
        date: "July 2022 - Present"
        content: |
          - Improved CLI tools and provisioning scripts written in Python.
          - Worked with Ansible playbooks to enhance deployments.
          - Utilized HAProxy to optimize load balancing of OpenVPN clients.
        featuredLink:
          enable: false
      - job: "Senior DevOps Engineer"
        company: "Ontraport"
        companyUrl: "https://ontraport.com"
        date: "April 2021 - July 2022"
        content: |
          - Maintained testing and deployment CI/CD pipelines.
          - Built automation tools in Go, Python, and Bash.
          - Migrated over 200 Git repositories from Bitbucket to Github.
          - Converted existing x86 container images to ARM.
          - Assisted in migrating databases from MySQL to PostgreSQL.
          - Managed multi-node Kubernetes clusters.
          - Implemented logging with Lua, PHP, Fluentbit, and Amazon S3.
        featuredLink:
          enable: false
      - job: "Senior Backend Engineer"
        company: "Ontraport"
        companyUrl: "https://ontraport.com"
        date: "August 2014 - April 2021"
        content: |
          - Designed applications in PHP/Hack, Redis/MySQL, and OpenResty.
          - Worked on converting existing stack to a container based infrastructure.
          - Created build pipelines in Bamboo, TeamCity, and Git.
          - Managed the backend engineer internship program.
          - Designed internal tooling for engineering and client-facing teams in React and PHP.
          - Helped develop and document a public-facing API.
          - Wrote and maintained unit tests.
        featuredLink:
          enable: false

  # Education
  education:
    enable: true
    items:
      - title: "B.S. Computer Science"
        school:
          name: "CSU Channel Islands"
          location: "Camarillo, CA"
        date: "August 2012 - June 2014"

      - title: "Computer Science & Architecture and Design"
        school:
          name: "Cuesta College"
          location: "San Luis Obispo, CA"
        date: "August 2009 - June 2012"

  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
        image: /images/achievment.jpg


  # projects
  projects:
    enable: false
    # title: "Custom Name"
    items:
      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://hugo-profile.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

  #Contact
  contact:
    enable: false
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: evan@evanjarrett.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blog"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/evanjarrett/
      linkedin: https://linkedin.com/in/evanjarrett/
      #twitter: https://twitter.com
      #instagram: https://instagram.com
      #facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
